Library/apps/lib/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Library.apps.lib import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_author/', views.AuthorCreate.as_view(), name='add_author'),
    path('add_debtor/', views.DebtorCreate.as_view(), name='add_debtor'),
    path('add_book/', views.BookCreate.as_view(), name='add_book'),
    path('add_pub_house/', views.PublishingHouseCreate.as_view(), name='add_pub_house'),
    path('list_author', views.AuthorRead.as_view(), name='list_author'),
    path('list_book', views.BookRead.as_view(), name='list_books'),
    path('list_debtor', views.DebtorRead.as_view(), name='list_debtor'),
    path('list_pub_house', views.PublishingHouseRead.as_view(), name='list_pub_house'),
    path('debtor/<int:pk>', views.DebtorUpdate.as_view(), name='update_debtor')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Library.apps.lib import views as lib_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('Library.apps.lib.urls')),
    path('', lib_views.index, name='index')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library/apps/lib/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    full_name = models.CharField(max_length=50, blank=False, verbose_name='Полное имя')
    birth_year = models.CharField(max_length=4, verbose_name='Год рождения')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Debtor(models.Model):
    full_name = models.CharField(max_length=50, blank=False, verbose_name='Имя должника')
    book = models.ManyToManyField('Book', related_name='book', blank=True, verbose_name='Должник')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Должник'
        verbose_name_plural = 'Должники'

    def get_absolute_url(self):
        return 'debtor/%i' % self.pk


class PublishingHouse(models.Model):
    pub_name = models.CharField(max_length=20, blank=False, verbose_name='Название издательства')

    def __str__(self):
        return self.pub_name

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'


class Book(models.Model):
    name = models.CharField(max_length=50, blank=False, verbose_name='Название книги')
    year = models.CharField(max_length=4, verbose_name='Год издания')
    pub_house = models.ManyToManyField(PublishingHouse, related_name='book', blank=True, verbose_name='Издательство')
    author = models.ManyToManyField(Author, related_name='book', blank=True, verbose_name='Автор')
    cost = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Стоимость в рублях')
    count = models.SmallIntegerField(default=1, blank=False, verbose_name='Количество')
    cover = models.ImageField(upload_to='covers/', blank=True, verbose_name='Обложка')

    def get_image(self):
        if not self.cover:
            self.cover = 'covers/no_img.jpg'
            return self.cover
        else:
            return self.cover

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

Library/apps/lib/forms.py
from django import forms
from .models import *


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class DebtorForm(forms.ModelForm):
    class Meta:
        model = Debtor
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class PublishingHouseForm(forms.ModelForm):
    class Meta:
        model = PublishingHouse
        fields = '__all__'

Library/apps/lib/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .forms import *
from .models import *


# Create your views here.
def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))


class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('list_author')
    template_name = 'lib/add_author.html'


class AuthorRead(ListView):
    model = Author
    template_name = 'lib/list_authors.html'


class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('list_books')
    template_name = 'lib/add_book.html'


class BookRead(ListView):
    model = Book
    template_name = 'lib/list_books.html'


class DebtorCreate(CreateView):
    model = Debtor
    form_class = DebtorForm
    success_url = reverse_lazy('list_debtor')
    template_name = 'lib/add_debtor.html'


class DebtorRead(ListView):
    model = Debtor
    template_name = 'lib/list_debtors.html'


class DebtorUpdate(UpdateView):
    form_class = DebtorForm
    model = Debtor
    template_name = 'lib/add_debtor.html'
    success_url = reverse_lazy('list_debtor')


class PublishingHouseCreate(CreateView):
    model = PublishingHouse
    form_class = PublishingHouseForm
    success_url = reverse_lazy('list_pub_house')
    template_name = 'lib/add_pub_house.html'


class PublishingHouseRead(ListView):
    model = PublishingHouse
    template_name = 'lib/list_pub_house.html'

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
    <title>Описание</title>
</head>
<body>
    {% block content %}
    {% endblock %}
    <nav class="nav">
        <a href="{% url 'list_books' %}" type="button" class="btn btn-primary btn-lg">Список книг</a>
        <a href="{% url 'list_author' %}" type="button" class="btn btn-primary btn-lg">Список авторов</a>
        <a href="{% url 'list_pub_house' %}" type="button" class="btn btn-primary btn-lg">Список издательств</a>
        <a href="{% url 'list_debtor' %}" type="button" class="btn btn-primary btn-lg">Список должников</a>
    </nav>
    <nav class="nav">
        <a href="{% url 'add_book' %}" type="button" class="btn btn-primary btn-lg">Добавить книгу</a>
        <a href="{% url 'add_author' %}" type="button" class="btn btn-primary btn-lg">Добавить автора</a>
        <a href="{% url 'add_pub_house' %}" type="button" class="btn btn-primary btn-lg">Добавить издательство</a>
        <a href="{% url 'add_debtor' %}" type="button" class="btn btn-primary btn-lg">Добавить должника</a>
    </nav>
</body>
</html>

templates/lib/add_author.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/add.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Добавить автора</title>
</head>
<body class="container">
    <h1>Добавление автора</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
        {% endfor %}
        </div>
        <input type="submit" value="Сохранить">
        </div>
    </form>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/add.js' %}"></script>
</html>

templates/lib/add_book.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/add.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Добавить книгу</title>
</head>
<body class="container">
    <h1>Добавление книги</h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
        </div>
        {% endfor %}
        <input type="submit" value="Сохранить">
    </form>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/add.js' %}"></script>
</html>

templates/lib/add_debtor.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/add.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Добавить должника</title>
</head>
<body class="container">
    <h1>Добавление должника</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
        {% endfor %}
        </div>
        <input type="submit" value="Сохранить">
        </div>
    </form>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/add.js' %}"></script>
</html>

templates/lib/add_pub_house.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/add.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Добавить издательство</title>
</head>
<body class="container">
    <h1>Добавление издательства</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
        {% endfor %}
        </div>
        <input type="submit" value="Сохранить">
        </div>
    </form>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/add.js' %}"></script>
</html>

templates/lib/index_message.html
{% extends 'index.html' %}
{% block content %}
    <nav class="nav">
        <h3>{{ add_sucess }}</h3>
    </nav>
{% endblock %}

templates/lib/list_authors.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Список авторов</title>
</head>
<body class="container">
	<h1>Список авторов:</h1>
	<table class="table table-bordered">
        <tbody>
            {% for author in object_list %}
		        <tr>
                    <td>
                        <h3>{{ author.full_name }}</h3>
                        <h4>Написал:</h4>
                        {% for book in author.book.annotate %}
                            <p>- {{ book }}</p>
                        {% endfor %}
                    </td>
                </tr>
		    {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'index' %}" type="button" class="btn btn-primary btn-lg">Назад</a>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
</html>

templates/lib/list_books.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Список книг</title>
</head>
<body class="container">
	<h1>Список книг:</h1>
	<table class="table table-bordered">
        <tbody>
            {% for book in object_list %}
                <tr>
                    <td>
                        <h3>Название: {{ book.name }}</h3>
                        <h4>Издательство: {{ book.pub_house.annotate.get }}</h4>
                        <h4>Автор: {{ book.author.annotate.get }}</h4>
                        <img src="{{ MEDIA_URL }}{{ book.get_image.url }}" height="200px"/>
                        <div>
                        <h4>Должники:</h4>
                            {% for debtor in book.book.annotate %}
                                <p>- {{ debtor }}</p>
                            {% endfor %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'index' %}" type="button" class="btn btn-primary btn-lg">Назад</a>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
</html>

templates/lib/list_debtors.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Список Должников</title>
</head>
<body class="container">
	<h1>Список должников:</h1>
		<table class="table table-bordered">
        <tbody>
            {% for debtor in object_list %}
                <tr>
                    <td>
                        <h3> Имя должника:<a href="{{ debtor.get_absolute_url }}">{{ debtor.full_name }}</a></h3>
                        <h4>Выдано:</h4>
                            {% for book in debtor.book.annotate %}
                                <p>- {{ book }}</p>
                            {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'index' %}" type="button" class="btn btn-primary btn-lg">Назад</a>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
</html>

templates/lib/list_pub_house.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
    {% load bootstrap3 %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <title>Список издательств</title>
</head>
<body class="container">
	<h1>Список издательств:</h1>
		{% for pub_house in object_list %}
		    <h3>{{ pub_house.pub_name }}</h3>
            <h4>{{ pub_house.publishing }}</h4>
            <h4>{{ pub_house.books }}</h4>
            <h4>{{ pub_house.book_set }}</h4>
            <h4>{{ pub_house.Meta }}</h4>
		{% endfor %}
    <a href="{% url 'index' %}" type="button" class="btn btn-primary btn-lg">Назад</a>
</body>
    <script src="{% bootstrap_jquery_url %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
</html>